name: KImageTerrain
main: com.gmail.kamilkime.kimageterrain.Main
version: 1.1
author: Kamilkime
commands:
  kterrain:
    aliases: [kimageterrain, kimaget, kimage]
permissions:
  kimageterrain.notify:
    default: op