name: ${project.name}
main: com.gmail.kamilkime.kimageterrain.Main
description: ${project.description}
version: ${project.version}
author: Kamilkime
commands:
  kterrain:
    aliases: [kimageterrain, kimaget, kimage]
permissions:
  kimageterrain.notify:
    default: op